### ISSUE TITLE
Quarg Ships

### ISSUE THREAD

**Issue by OcelotWalrus** [endless-sky/endless-sky-assets#142]
I can't find the Quarg Wardragon blender model. Same for the Quarg Skylark.

Is it normal that there is no Quarg ship model?

**Comment by lumbar527** [comment]
I found them, they just don't have the quarg prefix: https://github.com/endless-sky/endless-sky-assets/blob/master/ships/wardragon.blend, https://github.com/endless-sky/endless-sky-assets/blob/master/ships/skylark.blend

**Comment by OcelotWalrus** [comment]
Oh thanks! That help a lot.
